'use strict';

const { Octokit } = require('@octokit/rest');

async function main() {
  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.REPO_OWNER;
  const repo = process.env.REPO_NAME;
  const issueNumber = parseInt(process.env.ISSUE_NUMBER, 10);

  if (!token || !owner || !repo || isNaN(issueNumber)) {
    throw new Error('Missing required env vars: GITHUB_TOKEN, REPO_OWNER, REPO_NAME, ISSUE_NUMBER');
  }

  const branch = `feature/issue-${issueNumber}-implementation`;
  const octokit = new Octokit({ auth: token });

  const { data: issue } = await octokit.issues.get({ owner, repo, issue_number: issueNumber });

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: `feat: ${issue.title} (closes #${issueNumber})`,
    head: branch,
    base: 'main',
    body: [
      '## Summary',
      '',
      `Implementation of #${issueNumber}: ${issue.title}`,
      '',
      `Closes #${issueNumber}`,
      '',
      '## Test plan',
      '',
      '- [ ] Review implementation changes',
      '- [ ] Verify tests pass in CI',
      '- [ ] Check C4/ADR docs are updated if architecture changed',
      '',
      '🤖 Generated by the AI implementation agent',
    ].join('\n'),
  });

  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: issueNumber,
    body: `✅ Implementation complete. Pull request ready for review: ${pr.html_url}`,
  });

  console.log(`PR created: ${pr.html_url}`);
}

main().catch(err => {
  process.stderr.write(`create-pr failed: ${err.message}\n`);
  process.exit(1);
});
